module.exports =
  ADD_TODO: 'ADD_TODO'
  EDIT_TODO: 'EDIT_TODO'
  DELETE_TODO: 'DELETE_TODO'
  TOGGLE_TODO: 'TOGGLE_TODO'
  TOGGLE_ALL_TODOS: 'TOGGLE_ALL_TODOS'
  DELETE_ALL_COMPLETED_TODOS: 'DELETE_ALL_COMPLETED_TODOS'
