module.exports = require('../util/common-util').defineConstants [
  'ADD_TODO'
  'CHANGE_TODO_TEXT'
  'REMOVE_TODO'
  'TOGGLE_TODO'
  'TOGGLE_ALL_TODOS'
  'REMOVE_ALL_COMPLETED_TODOS'

  'WEBSERVICE_CALL_IS_RUNNING'
  'WEBSERVICE_ERROR_OCCURED'

  'WEBSERVICE_RECEIVE_ALL_TODOS'
  'WEBSERVICE_RECEIVE_TODO_CHANGES'
]
