module.exports = require('../../shared/util/common-util').defineConstants [
  'SHOW_ALL_TODOS'
  'SHOW_COMPLETED_TODOS'
  'SHOW_OPEN_TODOS'
  'REMOVE_ALL_COMPLETED_TODOS'

  'WEBSERVICE_CALL_IS_RUNNING'
  'WEBSERVICE_ERROR_OCCURED'

  'WEBSERVICE_RECEIVE_ALL_TODOS'
  'WEBSERVICE_RECEIVE_TODO_CHANGES'
]
